/* Automatically generated don't modify this file! */
/* eslint-disable perfectionist/sort-imports,perfectionist/sort-named-exports */

import AsyncValidator, { getValidationConfig, resetValidationConfig, setValidationConfig, zodRule } from 'async-validator-next'
import locale from './locale'
import type { InstallOptions } from './install'
import { install } from './install'
import { componentMap } from './components'

export type { InstallOptions }

export {
  CollapseTransition,
  Alert,
  Aside,
  Autocomplete,
  Avatar,
  Backtop,
  Badge,
  Breadcrumb,
  BreadcrumbItem,
  Button,
  ButtonGroup,
  Calendar,
  Card,
  Carousel,
  CarouselItem,
  Cascader,
  CascaderPanel,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Col,
  Collapse,
  CollapseItem,
  ColorPicker,
  ConfigProvider,
  Container,
  DatePicker,
  DatePickerV2,
  DateTable,
  Descriptions,
  DescriptionsItem,
  Dialog,
  Divider,
  Drawer,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Empty,
  Footer,
  Form,
  FormItem,
  Header,
  Icon,
  Image,
  ImageViewer,
  InfiniteScroll,
  Input,
  InputNumber,
  Link,
  Loading,
  Main,
  Menu,
  MenuItem,
  MenuItemGroup,
  Message,
  MessageBox,
  Notification,
  Option,
  OptionGroup,
  PageHeader,
  Pagination,
  Popconfirm,
  Popover,
  Progress,
  Radio,
  RadioButton,
  RadioGroup,
  Rate,
  Result,
  Row,
  Scrollbar,
  Select,
  Skeleton,
  SkeletonItem,
  Slider,
  Spinner,
  Statistic,
  Step,
  Steps,
  Submenu,
  Switch,
  TabPane,
  Table,
  TableColumn,
  Tabs,
  Tag,
  TimePicker,
  TimeSelect,
  Timeline,
  TimelineItem,
  Tooltip,
  Transfer,
  Tree,
  Upload,
  UploadList,
} from './components'

export {
  AsyncValidator,
  getValidationConfig,
  resetValidationConfig,
  setValidationConfig,
  zodRule,
}

export default {
  version: __ELEMENT_LEGACY_VERSION__,
  locale: locale.use,
  i18n: locale.i18n,
  install,
  ...componentMap,
  AsyncValidator,
  getValidationConfig,
  resetValidationConfig,
  setValidationConfig,
  zodRule,
}
